### ISSUE TITLE
Resource page view by teacher

### ISSUE THREAD

**Issue by supriti-mukherjee** [manasghosh81/MyMathsTesting#276]
login as teacher -> resources -> click on the chapter names one by one -> games is overlapping with the topics

![image30](https://cloud.githubusercontent.com/assets/11663550/12973522/fafe0904-d0d2-11e5-899f-65db782d4fbb.PNG)

**Comment by summar1** [comment]
FIxed now 

![image](https://cloud.githubusercontent.com/assets/16289032/12993556/cd7cdd84-d140-11e5-84cb-fa4e890a4a6c.png)

**Comment by supriti-mukherjee** [comment]
not fixed.

![defect5](https://cloud.githubusercontent.com/assets/11663550/13032296/8fe13280-d312-11e5-9b94-7582e45701b8.PNG)

**Comment by OUPGandhinagar** [comment]
Already Fixed & verified with Supriti.

**Comment by supriti-mukherjee** [comment]
Fixed
