### ISSUE TITLE
First time login--> the security question dropdown arrow should be more aligned towards right.

### ISSUE THREAD

**Issue by summar1** [manasghosh81/MyMathsTesting#393]
First time login--> the security question dropdown arrow should be more aligned towards right.

![image](https://cloud.githubusercontent.com/assets/16289032/13212970/82d76316-d96b-11e5-9c6f-70f56b90ca66.png)

**Comment by OUPGandhinagar** [comment]
Done in local & checked in SVN

**Comment by summar1** [comment]
still showing the same on QA

![image](https://cloud.githubusercontent.com/assets/16289032/13240768/4e245480-da0b-11e5-86c3-6d7e6f406cf2.png)

**Comment by OUPGandhinagar** [comment]
DONE in Local & checked in SVN.

**Comment by summar1** [comment]
Fixed now
