### ISSUE TITLE
Select All

### ISSUE THREAD

**Issue by supriti-mukherjee** [manasghosh81/MyMathsTesting#409]
Click on select all checkbox -> now uncheck a particular checkbox -> select all check is not going

**Comment by manasghosh81** [comment]
fixed

**Comment by supriti-mukherjee** [comment]
Not implemented in OUPADMIN- utilities,search school.
School Admin - View class details,utilities
Teacher-Search Task,search activities

**Comment by summar1** [comment]
![image](https://cloud.githubusercontent.com/assets/16289032/13295657/f17ac4e4-db4f-11e5-98e8-898e8e5164f1.png)

still exists

**Comment by summar1** [comment]
Fixed now
